# Generated by Django 4.2.3 on 2023-07-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_link_remove_search_links_list_search_links_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='links_list',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AddField(
            model_name='search',
            name='links_list',
            field=models.JSONField(default='abc'),
            preserve_default=False,
        ),
    ]
